In [1]:
#載入mnist數據集
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.shape)
len(train_labels)

11501568/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)


60000

In [2]:
train_labels[0:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [3]:
print(test_images.shape)
len(test_labels)

(10000, 28, 28)


10000

In [4]:
test_labels[0:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [5]:
#建立模型
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(
    optimizer = 'rmsprop',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

In [6]:
#將圖片標準化(normalization), 壓到0~1之間
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype('float32')/ 255

test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32')/ 255

In [8]:
#from keras.utils import to_categorical
#在Tensorflow2, Keras整合進去
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

train_labels[0:5]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [9]:
#進行訓練
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 9ms/step - loss: 0.2560 - accuracy: 0.9259
Epoch 2/5
469/469 [==============================] - 4s 8ms/step - loss: 0.1021 - accuracy: 0.9695
Epoch 3/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0684 - accuracy: 0.9794
Epoch 4/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0485 - accuracy: 0.9854
Epoch 5/5
469/469 [==============================] - 4s 8ms/step - loss: 0.0366 - accuracy: 0.9886


In [10]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
test_acc

313/313 [==============================] - 1s 2ms/step - loss: 0.0759 - accuracy: 0.9782


0.9782000184059143